### ISSUE TITLE
AdjScoreProteins errors: adjacency score for each feature pairError: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by classycammy** [CamaraLab/STvEA#8] opened 2020-11-16 00:10 UTC
Thanks very much for developing such a great useful tool for the use of CODEX analysis. I have no trouble running the package and the spatial analyses were really helpful for my image analysis. However, I have recently encounter the problem for running protein expression on the adjacent cells. Below is the error message: 

> protein_adj <- AdjScoreProteins(stvea_object, k=3, num_cores=8)
Creating permutation matrices - 77.365 seconds
Computing adjacency score for each feature pairError: $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In if (class(f) != "matrix") { :
  the condition has length > 1 and only the first element will be used
2: In if (class(f_pairs) == "list") { :
  the condition has length > 1 and only the first element will be used
3: In mclapply(1:nrow(f), function(i) as(t(sapply(1:nrow(permutations),  :
  all scheduled cores encountered errors in user code
4: In mclapply(work, worker, mc.cores = num_cores) :
  all scheduled cores encountered errors in user code

I am uncertain if I ran out of memory or cores? I have 24 cores in my computer and will able to increase if needed. I did adjust the k and num_cores parameters, however, I kept getting back these error messages. Any help will be deeply appreciated. Thanks very much.

**Comment by govekk** [comment] 2020-11-17 19:17
Hi, thanks for using our package! I'll need a bit more information to help with this:
1. Could you please run it with num_cores=1 and see if there is a different error? The one you are getting typically hides any errors in the parallelized code.
2. Are you running this on Windows, Mac, Linux or our Docker container?
3. How many cells and proteins do you have? It is possible that you are running out of memory if you have many proteins, which might require you to use fewer cores or manually input the protein pairs you are interested in.

**Comment by classycammy** [comment] 2020-11-23 04:10
Thanks so much for your response. I deeply appreciate it. In regards to your following questions:

**1. Could you please run it with num_cores=1 and see if there is a different error? The one you are getting typically hides any errors in the parallelized code.**

The errors are:
```
> protein_adj <- AdjScoreProteins(stvea_object, k=3, num_cores=1)
Creating permutation matricesError in ext[[class2]] : no such index at level 1
In addition: Warning messages:
1: In if (class(f) != "matrix") { :
  the condition has length > 1 and only the first element will be used
2: In if (class(f_pairs) == "list") { :
  the condition has length > 1 and only the first element will be used
```
Are there any tricks to generate out the full errors? I did try verbose but it's not included in the argument.

**2.     Are you running this on Windows, Mac, Linux or our Docker container?**

I am running in Linux. I also tried Mac and the same errors occurred.


3.     How many cells and proteins do you have? It is possible that you are running out of memory if you have many proteins, which might require you to use fewer cores or manually input the protein pairs you are interested in.

I have 150K cells and 38 protein markers.

I do appreciate any advises. Thanks so much.


Cheers
Cam

**Comment by govekk** [comment] 2020-11-23 17:19
Often calling traceback() right after you get an error can print out the full stack of that error in R. That would help me see if the error is occurring in our package or in an outside package we call. 

What version of R are you using? My guess is the warnings are caused by a recent change in R 4.0, where class() of a matrix is now ("matrix" "array"), not just "matrix". I don't believe this should be changing how the code runs, since the first element is still "matrix", but I will address the warning messages in a future commit. Thank you for bringing that to our attention.

It is possible the actual error is being caused by a similar change to R 4.0, as we have not tested the package on that R version since it was released in October. The code may run fine on your data in an earlier R version, but I appreciate any help you can give in figuring out this error so we can improve the package for the newest version.

Thanks!

**Comment by classycammy** [comment] 2020-11-24 00:10
See below for the print out:
```
> traceback()
9: possibleExtends(thisClass, Class)
8: isFALSE(ext)
7: as(t(sapply(1:nrow(permutations), function(j) f[i, ][permutations[j, 
       ]])), class(f))
6: FUN(X[[i]], ...)
5: lapply(X = X, FUN = FUN, ...)
4: mclapply(1:nrow(f), function(i) as(t(sapply(1:nrow(permutations), 
       function(j) f[i, ][permutations[j, ]])), class(f)), mc.cores = num_cores)
3: adjacency_score(adj_matrix, codex_protein_cut, protein_pairs, 
       c = c, num_cores = num_cores, num_perms = num_perms, perm_estimate = perm_estimate)
2: AdjScoreProteins.internal(knn_adj, stvea_object@codex_protein, 
       protein_pairs, c = c, num_cores = num_cores, num_perms = num_perms, 
       perm_estimate = perm_estimate)
1: AdjScoreProteins(stvea_object, k = 3, num_cores = 1)
```

Yes I am using R version 4.0.2 (2020-06-22).  I look forward to your next suggestion and recommendation as this package is super helpful in analysing interesting cell-to-cell protein markers. I appreciate it. Thanks very much!

**Comment by govekk** [comment] 2020-11-25 21:59
Thank you for your help with this. The error was caused by a similar change in the behavior of class() in our AdjacencyScore package, which this function uses. I have updated that package and it appears to be working. You will have to reinstall AdjacencyScore to apply the changes. Please let me know if there are any other issues.

**Closed by govekk** 2020-11-25 21:59 UTC

**Comment by classycammy** [comment] 2020-12-04 02:48
Hi - Thanks so much for the lovely update! I have some issues running it. Please see below

```
> protein_adj <- AdjScoreProteins(stvea_object, k=3, num_cores=8)
Creating permutation matrices - 69.43 seconds
Computing adjacency score for each feature pairError: $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In if (class(f) != "matrix") { :
  the condition has length > 1 and only the first element will be used
2: In if (class(f_pairs) == "list") { :
  the condition has length > 1 and only the first element will be used
3: In mclapply(1:nrow(f), function(i) as(t(sapply(1:nrow(permutations),  :
  all scheduled cores encountered errors in user code
4: In mclapply(work, worker, mc.cores = num_cores) :
  all scheduled cores encountered errors in user code
> traceback()
4: p.adjust(qqh$p, method = "BH")
3: adjacency_score(adj_matrix, codex_protein_cut, protein_pairs, 
       c = c, num_cores = num_cores, num_perms = num_perms, perm_estimate = perm_estimate)
2: AdjScoreProteins.internal(knn_adj, stvea_object@codex_protein, 
       protein_pairs, c = c, num_cores = num_cores, num_perms = num_perms, 
       perm_estimate = perm_estimate)
1: AdjScoreProteins(stvea_object, k = 3, num_cores = 8)
```

Could you please provide additional advise on whether it is my data or the code itself? I am running using my Linux/Ubuntu computer. Thanks so much. I really appreciate it again.

**Comment by govekk** [comment] 2020-12-04 16:26
Hi, it looks like you didn't reinstall the AdjacencyScore package or R didn't reload the package once installed. It worked for me to run devtools::install_github("CamaraLab/AdjacencyScore") and then restart my R session.

**Comment by classycammy** [comment] 2020-12-07 22:37
Hi, Thanks so much for the advises! It works like a charm. On a side note, if this is useful for others, I used num_cores=1 as R has difficulty with multi-thread processing using 8 cores. I deeply appreciate this @govekk
